spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2
server:
  port: 7777
  servlet:
    context-path: /musical-jukebox
logging:
  config: classpath:logback-spring.xml
---
spring:
  profiles: dev
  datasource:
    password: ""
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/test;DB_CLOSE_DELAY=-1
    username: "sa"